
auth.token=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

defaults.org=dashcode
defaults.project=react-native

defaults.url=https://sentry.io/
